export { default as IconHome } from './IconHome.vue'
export { default as IconExit } from './IconExit.vue'
export { default as IconArrow } from './IconArrow.vue'
export { default as IconGitogram } from './IconGitogram.vue'
export { default as IconFork } from './IconFork.vue'
export { default as IconStar } from './IconStar.vue'
export { default as IconClose } from './IconClose.vue'
